name: Build MiniToolbox (Windows)

on:
  # 手动触发
  workflow_dispatch:
  # 发布触发（仅 tag）
  push:
    tags: [ 'v*' ]

jobs:
  build-win:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Windows artifacts (no publish)
        env:
          # 禁用自动代码签名与自动发布
          CSC_IDENTITY_AUTO_DISCOVERY: false
        run: npm run build:win -- --publish=never

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MiniToolbox-Windows
          path: |
            dist/*.exe
            dist/*.7z
            dist/*.zip
            dist/*.yml
            dist/win-*/**
          if-no-files-found: warn
          retention-days: 7

  release:
    name: Attach artifacts to GitHub Release
    if: startsWith(github.ref, 'refs/tags/')
    needs: build-win
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: MiniToolbox-Windows
          path: dist

      - name: Create GitHub Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.exe
            dist/*.7z
            dist/*.zip
            dist/*.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


